// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khmimsqqpjzmysmsdidd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtobWltc3FxcGp6bXlzbXNkaWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjA0NzgsImV4cCI6MjA3MTI5NjQ3OH0.sx_U2v1ZWqXdVhu_daDxYPq0eYOzAeN7pxEhj1U-_-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});